- layout/console.xml
- styles/base/extrastyles.sass
- styles/console.sass
- styles/controls/avatar.sass
- Fix avatar.sass having incorrect style
- Get rid of some `@import`s
- Use `mono-spaced-font` helper class in console
> fix: minor styling problems

- .github/workflows/eslint.yml
- .gitignore
- .prettierignore
- .prettierrc
- scripts/chat.js
- scripts/common/eventdefinition.js
- scripts/common/formattext.js
- scripts/common/panelregistration.js
- scripts/controlslibrary.js
- scripts/intromovie.js
- scripts/loadingscreen.js
- scripts/mainmenu.js
This helps us enforce some style. 
CI will fail if there are formatting errors. I think it's reasonable to require the PR author to format and then force push. We could also setup this action to push formatted code on main, but I'm not a huge fan of automated pushes coming from CI.
> Add prettier check in CI

- styles/console.sass
The current font size is a bit hard to read for me. So I bumped it up to make it easier to read.
Feel free to knock it down a few if it's a bit too large.
comparison
> Bump up the console text size to 20

- layout/menu/addons.xml
- styles/mainmenu.sass
- styles/menu/addons.sass
Updated addons menu and fixed a bit of styling for main menu.
> Updated addons menu

- styles/hud/hud.sass
Fixes some of the hud styling.
> fix: Hud Positions

- layout/hud/bonecounts.xml
- layout/hud/hud.xml
- layout/hud/showpos.xml
- layout/showfps.xml
- styles/hud/bonecounts.sass
- styles/hud/showpos.sass
- styles/showfps.sass
These are just very basic so P2CE can run with the port of these panels (see red PR); should get someone to look over styling n such afterwards.
> showfps, showpos, and showbonecounts panels

- fonts/conf.d/41-repl-os-win.conf
- fonts/fonts.conf
> fix: Resolve a couple of fontconfig warnings

- domain_whitelist.kv3
Don't merge until internal PR is in
> feat: add domain whitelist

- layout/components/settings/enum-dropdown.xml
- layout/components/settings/enum.xml
- layout/components/settings/keybinder.xml
- layout/components/settings/slider.xml
- layout/components/settings/toggle.xml
- layout/components/show-fps.xml
- layout/hud/bone-counts.xml
- layout/hud/hint-text.xml
- layout/hud/hud.xml
- layout/hud/show-pos.xml
- layout/pages/controls-library.xml
- layout/pages/intro-movie.xml
- layout/pages/main-menu/main-menu.xml
- layout/pages/settings/audio.xml
- layout/pages/settings/input.xml
- layout/pages/settings/interface.xml
- layout/pages/settings/video.xml
- layout/util/global-popups.xml
- layout/util/popup-manager.xml
- scripts/pages/intro-movie.js
- scripts/pages/main-menu/main-menu.js
- scripts/pages/settings/page.js
- scripts/pages/settings/settings.js
- styles/components/settings.scss
- styles/hud/hud.scss
- styles/pages/intro-movie.scss
Pretty much just a find and replace.
**Do not merge until the internal PR goes in!**
> Strip 'Chaos' prefix from panel and event names

- layout/pages/main-menu/main-menu.xml
This isn't even a "concept", it's just a placeholder!
> feat: change beta UI disclaimer

- layout/components/version-info.xml
- scripts/components/version-info.js
- scripts/util/panel-registration.js
- styles/components/version-info.scss
Originally by Erin in #59, but updated to scss and such.
Full credit to Erin and I've added them as co-author.
Closes #59
> feat: Initial VersionInfo component

- layout/pages/loading-screen.xml
- scripts/pages/loading-screen.js
- styles/pages/loading-screen.scss
This is a essentially just a port of what we had before stripping out the UI.
Moved the loading bar to the bottom center of the screen though.
Looks pretty sick with Pivot's new loading screen renders :D
> feat: Add portal 2-like loading screen

- .github/workflows/build.yml
- .gitignore
- .gitmodules
- .prettierignore
- layout/components/color-display.xml
- layout/components/color-picker.xml
- layout/components/graphs/line-graph.xml
- layout/components/range-color-display.xml
- layout/components/version-info.xml
- layout/hud/console-notify.xml
- layout/hud/static-menu.xml
- layout/modals/popups/color-picker.xml
- layout/modals/popups/import-export-settings.xml
- layout/modals/popups/playtest-consent.xml
- layout/modals/popups/range-color-profile-name.xml
- layout/pages/console.xml
- layout/pages/controls-library.xml
- layout/pages/intro-movie.xml
- layout/pages/loading-screen.xml
- layout/pages/main-menu/main-menu.xml
- layout/pages/settings/audio.xml
- layout/pages/settings/input.xml
- layout/pages/settings/interface.xml
- layout/pages/settings/settings.xml
- layout/pages/settings/video.xml
- package-lock.json
- package.json
- panorama.cfg
- scripts/pages/loading-screen.ts
- tsconfig.json
Adds support for TypeScript alongside JS. We can port the old scripts to TS piecemeal or as needed.
* Add support for TS
* Run `tsc` in CI
* Port loading-screen.js to typescript
* Refactor XML files to work with new build scheme
> TypeScript support

- layout/pages/controls-library.xml
- scripts/pages/main-menu/main-menu.ts
Ports the main menu script to typescript, bumps types submodule and fixes the controls library.
Just playing around with typescript mainly, please review so I can learn!
> More typescript porting

- scripts/pages/main-menu/main-menu.ts
- styles/core/animations.scss
- styles/pages/main-menu.scss
I felt like adding it. It's good example code anyway.
> feat: Support background maps on the main menu

- build.sh
- layout/pages/loading-screen.xml
- layout/pages/main-menu/addons.xml
- layout/pages/main-menu/campaigns.xml
- layout/pages/main-menu/main-menu.xml
- panorama.cfg
- tsconfig.json
> Use built-in typescript compiler

- layout/hud/show-pos.xml
Updates show pos to add missing values, should be on par with original vgui one
> Update show pos to add missing values

- layout/components/version-info.xml
- layout/pages/main-menu/main-menu.xml
- scripts/components/version-info.js
- styles/components/version-info.scss
> Make Version Info styled/show up

- layout/components/version-info.xml
- styles/components/version-info.scss
> version-info: Styling changes to better match the rest of the UI

- layout/pages/settings/customization.xml
Adds some more customizations to the customization menu. Didn't bother exposing the rest of the turret/energy ball light tweaks, since that'd add quite a bit of clutter.
Relies on https://github.com/StrataSource/p2ce-game/pull/113 for localizations, so PLEASE merge that too.
> feat: Add a few more items to the customizations menu
